---
kind: pipeline
type: docker
name: sqlack

steps:
  - name: lint
    image: python:3.7
    commands:
      - pip install -r test/dev-requirements.txt
      - flake8 pg_client/ --verbose
      - flake8 handler.py --verbose

  - name: test
    image: python:3.7
    commands:
      - pip install -r requirements.txt
      - pip install -r test/dev-requirements.txt
      - nosetests -v --with-coverage --cover-package ingestion --cover-min-percentage=50

  - name: build
    image: python:3.7
    commands:
      - pip install -r requirements.txt -t requirements
      # - mv requirements/* ./
    when:
      event: push
      branch: [develop, master]

  - name: deploy-dev
    image: node:alpine
    commands:
      - npm install -g serverless
      - npm install
      - echo $DB_HOST >> secrets.dev.yml
      - echo $DB_PORT >> secrets.dev.yml
      - echo $DB_NAME >> secrets.dev.yml
      - echo $DB_USERNAME >> secrets.dev.yml
      - echo $DB_PASSWORD >> secrets.dev.yml
      - serverless deploy -s dev --verbose

    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      DB_HOST: 
        from_secret: db_host_dev
      DB_PORT:
        from_secret: db_port_dev
      DB_NAME:
        from_secret: db_name_dev
      DB_USERNAME:
        from_secret: db_username_dev
      DB_PASSWORD:
        from_secret: db_password_dev
        
    when:
      status: success
      event: push
      branch: develop

  - name: deploy-prod
    image: node:alpine
    commands:
      - npm install -g serverless
      - npm install
      - echo $DB_HOST >> secrets.prod.yml
      - echo $DB_PORT >> secrets.prod.yml
      - echo $DB_NAME >> secrets.prod.yml
      - echo $DB_USERNAME >> secrets.prod.yml
      - echo $DB_PASSWORD >> secrets.prod.yml
      - serverless deploy -s prod --verbose
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      DB_HOST: 
        from_secret: db_host_prod
      DB_PORT:
        from_secret: db_port_prod
      DB_NAME:
        from_secret: db_name_prod
      DB_USERNAME:
        from_secret: db_username_prod
      DB_PASSWORD:
        from_secret: db_password_prod
    when:
      status: success
      event: push
      branch: master

  # - name: notify
  #   image: plugins/slack
  #   channel: guillaume
  #   webhook: https://hooks.slack.com/services/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
  #   username: drone
  #   when:
  #     status: [ success, failure ]
  #     event: [ push, pull_request ]
  # 
